ssh_authorized_keys:
- github:clwillingham
write_files:
- encoding: ""
  content: |-
    include_ping_test=yes
    ping_test_host=github.com
    timeout=120
  owner: root
  path: /etc/conf.d/net-online
  permissions: '0755'
init_cmd:
- "echo hello, init command"
boot_cmd:
- "echo hello, boot command"
run_cmd:
- "echo hello, run command"
k3os:
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  labels:
    region: us-east-l
  k3s_args:
  - server
  - "--cluster-init"
